### ISSUE TITLE
[Opencast] If a single video is uploaded with presentation flavor, paella won't play the presentation audio track

### ISSUE THREAD

**Issue by mliradelc** [polimediaupv/paella-core#14]
Hi.

We found that if you upload in Opencast a single video with the presentation flavor, paella won't detect the audio track from this video.

The error that shows Paella is:
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getAudioTracks')
    at M.<anonymous> (StreamProvider.js:375:31)
    at l (paella-core.js:2:560261)
    at Generator._invoke (paella-core.js:2:560049)
    at Generator.next (paella-core.js:2:560686)
    at C (initFunctions.js:24:8)
    at a (initFunctions.js:24:8)
    at initFunctions.js:24:8
    at new Promise (<anonymous>)
    at M.<anonymous> (initFunctions.js:24:8)
    at M.<anonymous> (StreamProvider.js:374:2)
```

Paella 6 works without this issue.

**Comment by ferserc1** [comment]
This bug is not related with Paella core library. The correct place to post paella player issues should be the opencast repository, but they have not yet accepted the pull request with the implementation we have prepared. 

I will investigate the problem in the opencast fork we have, but from now on I would prefer that you use the paella player mailing list to post issues that are not related to paella-core and with any other of our repositories.
