### ISSUE TITLE
paella-core >= 1.25.1. Uncaught (in promise) Error: Error loading video: [object MediaError] MEDIA_ELEMENT_ERROR: Format error  

### ISSUE THREAD

**Issue by renefs** [polimediaupv/paella-core#215]
Hi, I noticed the following error on `paella-core>=1.25.1`. It happens when we try to access a resource that is protected (cors required) but it works fine when the resource is public.

```
caught (in promise) Error: Error loading video: <URL>. Code: [object MediaError] MEDIA_ELEMENT_ERROR: Format error
    at n (es.upv.paella.mp4VideoFormat.js:299:32)
    at es.upv.paella.mp4VideoFormat.js:307:60
```

```
caught (in promise) TypeError: Cannot read properties of undefined (reading 'indexOf')
    at x.<anonymous> (VideoContainer.js:457:54)
    at l (VideoContainer.js:2:1)
    at Generator.<anonymous> (VideoContainer.js:2:1)
    at Generator.next (VideoContainer.js:2:1)
    at It (VideoContainer.js:2:1)
    at a (VideoContainer.js:2:1)
    at VideoContainer.js:2:1
    at new Promise (<anonymous>)
    at x.<anonymous> (VideoContainer.js:2:1)
    at x.<anonymous> (VideoContainer.js:478:6)
```

I think the error might be related to this commit: https://github.com/polimediaupv/paella-core/commit/aa744f867475aefdcf4a0b9adfec937571f6988d

```js
this.element.setAttribute("crossorigin","");
```

**Comment by ferserc1** [comment]
Starting from version 1.28 you can customize this attribute by configuring the HLS or MP4 video plugin. If you set the `crossOrigin` setting to `false` in the plugin configuration, the `crossorigin` attribute will not be added:

```json
"es.upv.paella.mp4VideoFormat": {
    "enabled": true,
    "crossOrigin": false,
    ...
},
"es.upv.paella.hlsVideoFormat": {
    "enabled": true,
    "crossOrigin": false,
    ...
}
```
